version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-cli
    versions:
    - 2.19.1
    - 2.19.2
    - 3.2.0
    - 3.4.0
  - dependency-name: "@material-ui/styles"
    versions:
    - 4.11.4
  - dependency-name: gatsby-plugin-offline
    versions:
    - 4.1.0
    - 4.2.0
  - dependency-name: gatsby
    versions:
    - 3.1.1
